# Generated by Django 2.2.5 on 2020-06-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200520_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='education',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='country',
        ),
    ]
